
# ~/.dbt/profiles.yml
brewery:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/data/duckdb/brewery.duckdb      
      schema: main
      external_root: /opt/airflow/data
      #external_root: ../data
      #path: ../data/duckdb/brewery.duckdb
  target: ci
  outputs:
    ci:
      type: duckdb
      path: ":memory:"
      threads: 1
      

